# Generated by Django 4.2.1 on 2023-11-23 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SeriesApp', '0001_initial'),
        ('movieapp', '0022_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(default=uuid.UUID('45cb1ac0-c33a-4526-85b7-5f7fcddfec0c'), max_length=225)),
                ('is_movie', models.BooleanField(default=False)),
                ('is_series', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SeriesApp.series')),
            ],
        ),
    ]
