# Generated by Django 4.2.1 on 2023-11-25 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('957e61b9-b157-4621-8453-409248949ecd'), max_length=225),
        ),
    ]
