# Generated by Django 4.2.1 on 2023-11-27 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0002_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('c7623f30-1d3f-4838-b76f-df4b2ea2d53a'), max_length=225),
        ),
    ]
