# Generated by Django 4.2.1 on 2023-11-28 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0004_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('2f049fd2-814f-4988-9a29-606a4eb515c1'), max_length=225),
        ),
    ]
