# Generated by Django 4.2.1 on 2023-12-11 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0005_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('235af7c7-4c5f-4e07-8bb1-e187ec4d37d7'), max_length=225),
        ),
    ]
