# Generated by Django 4.2.1 on 2023-12-11 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0006_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('0a0dbe53-a367-4333-845c-7423fa9e6974'), max_length=225),
        ),
    ]
