# Generated by Django 4.2.1 on 2023-12-11 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0007_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('db44edeb-11ef-4a1f-9561-884bc9b02b46'), max_length=225),
        ),
    ]
