# Generated by Django 4.2.1 on 2023-12-11 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0008_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('27c2f7f5-6241-41e8-8d6c-77acbc6d921f'), max_length=225),
        ),
    ]
