# Generated by Django 4.2.1 on 2023-12-30 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0010_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('d900aea8-cef4-483c-b0a0-fc5882a3b4be'), max_length=225),
        ),
    ]
