# Generated by Django 4.2.1 on 2023-12-30 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0011_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('037ed380-bb1b-43b2-8df2-ecc1c6099029'), max_length=225),
        ),
    ]
