# Generated by Django 4.2.1 on 2023-12-30 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0012_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('9c788351-21f6-4735-a939-98e0b10cf113'), max_length=225),
        ),
    ]
