# Generated by Django 4.2.1 on 2023-12-30 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0013_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('207ee59b-fa9f-4c3a-bc33-1babe19ade8e'), max_length=225),
        ),
    ]
