# Generated by Django 4.2.1 on 2023-12-30 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0014_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('3970d23b-5a88-43d5-95de-8b61bd663905'), max_length=225),
        ),
    ]
