# Generated by Django 4.2.1 on 2023-12-30 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0015_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('8771191d-f957-4799-8422-66aa01042fb0'), max_length=225),
        ),
    ]
