# Generated by Django 4.2.1 on 2023-12-30 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0016_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('ce21d012-7686-49ca-8d5f-f2f61d603f40'), max_length=225),
        ),
    ]
