# Generated by Django 4.2.1 on 2024-03-14 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0017_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('02d0d02e-8c84-48a3-b871-2dab5ee88cb9'), max_length=225),
        ),
    ]
