# Generated by Django 4.2.1 on 2024-03-14 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0018_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('219edb03-fe79-4e58-ab9e-cef8d64d67f9'), max_length=225),
        ),
    ]
