# Generated by Django 5.0.3 on 2024-03-15 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0019_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('cfd32e2a-82bd-4782-8e9f-93816e076c68'), max_length=225),
        ),
    ]
