# Generated by Django 5.0.3 on 2024-03-15 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0020_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('4afe28c7-2424-4294-8bff-bf46c039a9f8'), max_length=225),
        ),
    ]
