# Generated by Django 5.0.3 on 2024-03-15 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0021_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('b2955fd9-6adf-4f38-833c-41e76861a1ce'), max_length=225),
        ),
    ]
