# Generated by Django 5.0.3 on 2024-03-15 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0022_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('62eae925-8304-43d9-ba23-5273b71aab5f'), max_length=225),
        ),
    ]
