# Generated by Django 5.0.3 on 2024-03-15 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0023_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('1e1bcb3f-cbe7-4cc9-8151-50312942fdfc'), max_length=225),
        ),
    ]
