# Generated by Django 5.0.3 on 2024-03-15 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0024_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('1f3d7ea3-21e6-4fe3-a76d-e8a0acd44408'), max_length=225),
        ),
    ]
