# Generated by Django 5.0.3 on 2024-03-15 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamsApp', '0025_alter_stream_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.CharField(default=uuid.UUID('0c870f34-f7a4-41dd-b110-1861b7e41dbf'), max_length=225),
        ),
    ]
