# Generated by Django 4.0.4 on 2023-04-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Globals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('episode_num', models.IntegerField(default=1)),
                ('video', models.CharField(blank=True, max_length=10000, null=True)),
                ('sub_title_lang', models.CharField(blank=True, max_length=225, null=True)),
                ('srclang', models.CharField(blank=True, max_length=225, null=True)),
                ('sub_title_file', models.CharField(blank=True, max_length=1000, null=True)),
                ('sub_title_lang2', models.CharField(blank=True, max_length=225, null=True)),
                ('srclang2', models.CharField(blank=True, max_length=225, null=True)),
                ('sub_title_file2', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('dou', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='series_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20000)),
                ('info', models.TextField()),
                ('thumbnail', models.FileField(upload_to='thumb/series/')),
                ('age', models.CharField(default=13, max_length=20)),
                ('rating', models.CharField(max_length=100)),
                ('is_series_new', models.BooleanField(default=False)),
                ('premier', models.BooleanField(default=False)),
                ('series_air_date', models.DateField(auto_now_add=True)),
                ('year_range', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('draft', models.BooleanField(default=False)),
                ('clicks', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(default='anime', max_length=200)),
                ('watch_hours', models.FloatField(default=0.0)),
                ('genre1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_category1', to='Globals.category')),
                ('genre2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_category2', to='Globals.category')),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_num', models.CharField(max_length=100)),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('collapse', models.CharField(blank=True, max_length=100, null=True)),
                ('series_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_val', to='SeriesApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='episode_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5000)),
                ('body', models.TextField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_reviews', to='SeriesApp.episode')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SeriesApp.series')),
            ],
        ),
        migrations.CreateModel(
            name='episode_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_comments', to='SeriesApp.episode')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SeriesApp.series')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='SeriesApp.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_epi', to='SeriesApp.series'),
        ),
    ]
