# Generated by Django 4.2.1 on 2023-11-23 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=True)),
                ('pricing_plan', models.CharField(blank=True, default='Free', max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.IntegerField(blank=True, default=0, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
