# Generated by Django 4.2.1 on 2023-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_created_watch_parties',
            field=models.IntegerField(default=0),
        ),
    ]
