# Generated by Django 4.0.4 on 2022-12-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0018_alter_episode_sub_title_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='srclang',
            new_name='srclanguage',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='srclang2',
            new_name='srclanguage2',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='sub_title_lang',
            new_name='sub_title_language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='sub_title_lang2',
            new_name='sub_title_language2',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='new',
            new_name='is_series_new',
        ),
    ]
