# Generated by Django 4.0.4 on 2023-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0019_rename_cat_movie_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
