# Generated by Django 4.0.4 on 2023-04-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SeriesApp', '0001_initial'),
        ('Globals', '0001_initial'),
        ('movieapp', '0020_movie_watch_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season_val',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='series_name',
        ),
        migrations.RemoveField(
            model_name='episode_comment',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='episode_comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='episode_comment',
            name='series_name',
        ),
        migrations.RemoveField(
            model_name='episode_review',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='episode_review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='episode_review',
            name='series_name',
        ),
        migrations.DeleteModel(
            name='rate',
        ),
        migrations.RemoveField(
            model_name='season',
            name='series_name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre1',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre2',
        ),
        migrations.DeleteModel(
            name='series_comment',
        ),
        migrations.DeleteModel(
            name='year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1', to='Globals.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='Globals.category'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='series_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SeriesApp.series'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='episode',
        ),
        migrations.DeleteModel(
            name='episode_comment',
        ),
        migrations.DeleteModel(
            name='episode_review',
        ),
        migrations.DeleteModel(
            name='season',
        ),
        migrations.DeleteModel(
            name='series',
        ),
    ]
