# Generated by Django 4.2.1 on 2023-11-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0021_remove_episode_season_val_remove_episode_series_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
