# Generated by Django 4.2.1 on 2023-11-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0001_initial'),
        ('movieapp', '0022_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre2',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='Globals.category'),
        ),
    ]
