# Generated by Django 4.2.1 on 2023-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0023_remove_movie_genre1_remove_movie_genre2_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('cartoon', 'cartoon')], max_length=200),
        ),
    ]
