# Generated by Django 5.0.3 on 2024-03-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0032_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
