# Generated by Django 5.0.3 on 2024-03-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0034_rename_age_movie_rated_movie_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, choices=[('20 min', '20 min'), ('30 min', '30 min'), ('40 min', '40 min'), ('50 min', '50 min'), ('60 min', '60 min'), ('70 min', '70 min'), ('80 min', '80 min'), ('90 min', '90 min'), ('100 min', '100 min'), ('110 min', '110 min'), ('120 min', '120 min'), ('130 min', '130 min'), ('140 min', '140 min'), ('150 min', '150 min'), ('160 min', '160 min'), ('170 min', '170 min'), ('180 min', '180 min'), ('190 min', '190 min'), ('200 min', '200 min'), ('210 min', '210 min'), ('220 min', '220 min'), ('230 min', '230 min'), ('240 min', '240 min'), ('250 min', '250 min'), ('260 min', '260 min'), ('270 min', '270 min'), ('280 min', '280 min'), ('290 min', '290 min'), ('300 min', '300 min'), ('310 min', '310 min')], max_length=100, null=True),
        ),
    ]
