# Generated by Django 5.0.3 on 2024-03-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Globals', '0005_country'),
        ('movieapp', '0036_alter_movie_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='country', to='Globals.country'),
        ),
    ]
